name: Upload Source Documents

on:
  workflow_dispatch:

jobs:
  push_files_to_crowdin:
    name: Push files to Crowdin
    if: github.repository == 'go-task/task'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload source documents
        run: task crowdin:push
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        working-directory: ./docs
